M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Wed 05 Oct 2022 01:28:34 PM EDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-05T13:28:34-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0472
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0512
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0551
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T5C0.0591
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T6C0.0709
%
G90
G05
T1
X9.7Y-2.0079
X9.7Y-2.9921
T2
X5.3Y-2.6
X5.3Y-4.8
X5.7Y-4.2
X6.2535Y-4.9
X7.9Y-4.2
X7.9465Y-4.9
X8.1535Y-4.9
X9.8465Y-4.9
T3
X6.0Y-2.3
X6.2Y-2.3
X6.6Y-2.3
X6.8Y-2.3
X9.9Y-3.3
X9.9Y-3.5
T4
X7.2764Y-2.3
X9.3236Y-2.3
T5
X8.1197Y-3.7
X9.6Y-3.7
T6
X7.2Y-3.1341
X7.2Y-3.6656
T0
M30
